version: '3'

services:
  ci-build:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./NetSnake.sln && dotnet publish ./NetSnake.sln -c Release -o ./obj/Docker/publish"
